[tox]
minversion = 4.0
envlist = py314,lint

[testenv]
commands = pytest {posargs}
extras = test

[testenv:lint]
commands = ruff check .
extras = test

[testenv:cover]
commands = pytest --cov=hflossk {posargs}
extras = test
